packages:
  ApolloAutomation.H-1: # name of package/project
#    url: https://github.com/ApolloAutomation/H-2 # url of the repository
    url: https://github.com/lcgreenwald/H-2 # url of the repository
    ref: main # branch, tag or commit SHA
    files:  # Path to config from base repo URL
      - Integrations/ESPHome/Core.yaml
    refresh: 1min # how often to sync updates from the remote url
