text:
  - platform: template
    name: "Song Text 1"
    id: !extend song_1
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "jingle:d=8,o=5,b=120:e6,e6,e.6,16p,e6,e6,e.6,16p,e6,g6,c.6,16d6,e.6,p,f6,f6,f.6,16f6,f6,e6,e6,16e6,16e6,e6,d6,d6,e6,d.6,16p,g6,p,e6,e6,e.6,16p,e6,e6,e.6,16p,e6,g6,c.6,16d6,2e6,f6,f6,f.6,16f6,f6,e6,e6,16e6,16e6,g6,g6,f6,d6,2c6;"
  - platform: template
    name: "Song Text 2"
    id: !extend song_2
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "rudolph:d=4,o=5,b=125:8g.,16a,8p,16g.,e,c6,a,2g.,8g.,16a,8g.,16a,g,c6,1b,8f.,16g,8p,16f.,d,b,a,2g.,8g.,16a,8g.,16a,g,a,1e,8g.,16a,8p,16g.,e,c6,a,1g,8g.,16a,8g.,16a,g,c6,1b,8f.,16g,8p,16f.,d,b,a,1g,8g.,16a,8g.,16a,g,d6,2c6;"
  - platform: template
    name: "Song Text 3"
    id: !extend song_3
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "snow:d=4,o=5,b=125:8c,8c,8c6,8c6,a#,a,g,f,2c,8c,16c,g.,8f,g.,8f,e,2c,d,8d6,8d6,c6,a#,a,2g.,8e.6,16d6,c6,8c.6,16a#,a,8a.,16g,2f.,c,8c6,8c6,a#,a,g,f,2c,8c.,16c,g.,8f,g.,8f,e,2c,d,8d6,8d6,c6,a#,a,2g.,8e.6,16d6,c6,8c.6,16a#,a,8a.,16g,2f.;"
  - platform: template
    name: "Song Text 4"
    id: !extend song_4
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "carolbells:d=4,o=5,b=200:g,8f#,8g,e,g,8f#,8g,e,g,8f#,8g,e,g,8f#,8g,e,b,8a,8b,g,b,8a,8b,g,b,8a,8b,g,b,8a,8b,g,e6,8e6,8e6,8d6,8c6,b,8b,8b,8a,8g,a,8a,8a,8b,8a,e,8e,8e,e,8b4,8c#,8d#,8e,8f#,8g,8a,8b,a,g,8b4,8c#,8d#,8e,8f#,8g,8a,8b,a,g;"
